CREATE TABLE joins_homework.CUSTOMERS (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    surname VARCHAR(35) NOT NULL,
    age INT,
    phone_number VARCHAR(15) NOT NULL
);

CREATE TABLE joins_homework.ORDERS(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    customer_id INT,
    product_name TEXT NOT NULL,
    amount INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES joins_homework.CUSTOMERS(id)
);